spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/heroku_83703ac4ba15791
    username: b3386e7899d43d
    password: 75124ef2
    driver-class-name: com.mysql.jdbc.Driver
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: create
liquibase:
  enabled: false 
  change-log: classpath:/db/changelog/master.xml

logging:
  level: 
    org.springframework.web: DEBUG