spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/heroku_7bd10a1f96e1a60
    username: b98a36d3099d76
    password: 61b9583d
    driver-class-name: com.mysql.jdbc.Driver
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: create
liquibase:
  enabled: false 
  change-log: classpath:/db/changelog/master.xml

logging:
  level: 
    org.springframework.web: DEBUG