spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/fintech_ws_new_2
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: create
liquibase:
  enabled: false 
  change-log: classpath:/db/changelog/master.xml

logging:
  level: 
    org.springframework.web: DEBUG