spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintech_ws
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

liquibase:
  enabled: false 
  change-log: classpath:/db/changelog/master.xml

logging:
  level: 
    org.springframework.web: DEBUG